services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: skill-map

  server:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile.server
    ports:
      - 3001:3001
    volumes:
      - ../../:/app:cached
    env_file:
      - server.env

  server-seed:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile.server-seed
    volumes:
      - ../../:/app:cached
    env_file:
      - server.env

  client:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile.client
    ports:
      - 3000:3000
    volumes:
      - ../../:/app:cached
